# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the develop branch
  pull_request:
    branches: [ develop ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install .NET 7.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 7.0.x
          
      - name: Restore NewPlatform.Flexberry.Caching.sln
        run: dotnet restore NewPlatform.Flexberry.Caching.sln
        
      - name: Install xunit.runner.console
        run: nuget install xunit.runner.console -Version 2.4.1 -OutputDirectory testrunner
        
      - name: Compile code
        run:  dotnet build /p:Configuration=Debug NewPlatform.Flexberry.Caching.sln 

      - name: Run dotnet tests
        run: dotnet test ./NewPlatform.Flexberry.Caching.Tests/bin/Debug/net7.0/NewPlatform.Flexberry.Caching.Tests.dll

      - name: Run mono tests
        run: mono ./testrunner/xunit.runner.console.2.4.1/tools/net461/xunit.console.exe ./NewPlatform.Flexberry.Caching.Tests/bin/Debug/net461/NewPlatform.Flexberry.Caching.Tests.dll
